export const loremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rutrum congue tincidunt. Mauris finibus eu nisl eu consequat. Maecenas ac vehicula elit, in congue lectus. Aliquam fermentum, dui ut rhoncus tincidunt, tortor ligula vulputate lorem, eget elementum felis dui nec risus. Maecenas in quam interdum, lacinia nulla vel, faucibus enim. Vivamus ullamcorper semper mi vitae feugiat. Donec efficitur scelerisque ante, vel blandit neque consectetur at. Nam eget pharetra diam. Maecenas a lacus id mauris varius volutpat eget et est. Sed sed pretium neque. Quisque egestas ex vel lectus fermentum, nec vulputate leo mollis. Curabitur id enim turpis. Pellentesque fringilla nisl sem, non eleifend lorem dignissim ut.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc semper nibh quis erat vehicula, eu feugiat turpis congue. Cras cursus nibh eu congue tincidunt. Proin in mauris lectus. Curabitur lobortis iaculis ipsum at ornare. Pellentesque vehicula urna mauris, non vestibulum sapien placerat in. Duis at magna tortor. Sed in commodo velit. Aliquam at maximus eros.

Nunc hendrerit eleifend aliquam. Morbi ante ante, condimentum a magna ut, dignissim congue nisl. Nullam viverra ut nibh ac dictum. Mauris faucibus, lectus eget fermentum egestas, nisi enim hendrerit dolor, non iaculis felis sapien eget ligula. Fusce nec nunc varius, fermentum purus id, tristique quam. Nam suscipit justo leo. Praesent tempor diam eget mi ultricies hendrerit. Etiam eget lacinia magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur convallis ipsum nisl, et aliquam nulla consequat a. Ut ultrices nibh felis, lacinia finibus augue ultricies et. Nam eget placerat neque. Morbi posuere mi nec tellus posuere maximus.

Phasellus tincidunt odio at lobortis egestas. Maecenas vehicula quam ac ultricies lacinia. Fusce sit amet neque ultrices, blandit sem non, dapibus massa. Curabitur vulputate justo a mi eleifend, non placerat arcu tincidunt. Sed odio felis, vulputate ut convallis ac, suscipit id odio. Nulla imperdiet faucibus finibus. Fusce justo augue, dictum a risus quis, iaculis sagittis tellus. Nulla vitae neque id urna dapibus consequat. Vestibulum pretium quam augue, vel lobortis ex maximus ut. Suspendisse volutpat at mi et gravida.

Sed sollicitudin tortor at augue malesuada pellentesque ut sed risus. Donec in hendrerit lacus, dignissim bibendum justo. Sed aliquam aliquam nulla, id luctus felis. Etiam justo dui, aliquam ut hendrerit ac, placerat finibus tortor. Aliquam sit amet consectetur odio. Duis tincidunt diam nec lectus euismod, at semper enim porttitor. Nullam odio enim, ultricies vitae tristique eu, aliquam eget nulla. Maecenas tincidunt auctor facilisis. Aliquam ante erat, eleifend vitae scelerisque quis, dignissim a erat. Cras volutpat iaculis ultrices. Nam nec lorem vitae mauris dictum auctor eget quis elit. In quis lectus ante. Etiam pellentesque, justo at imperdiet euismod, lectus elit tincidunt nunc, ut sollicitudin lacus lorem ut est. Donec eget bibendum augue. Curabitur pulvinar ex ac quam gravida volutpat. Cras volutpat eleifend nisl vitae posuere.`;
